version: "3.9"
services:
  game:
    stdin_open: true
    build:
      context: .
    volumes:
      - ./:/excalibur
      - /node_modules
    ports:
      - "1234:1234"
    container_name: excalibur_container
    command: yarn start
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true